### Get all (local)
GET http://localhost:8080/contacts

### Get one (local)
GET http://localhost:8080/contacts/6a021681e7af8279068f4b2e

### Get all (Render)
GET https://cse-341-project1-kvte.onrender.com/contacts

### Get one (Render)
GET https://cse-341-project1-kvte.onrender.com/contacts/6a021681e7af8279068f4b2e