### LOCAL — Get all
GET http://localhost:8080/contacts

### LOCAL — Get single (Bob Ross)
GET http://localhost:8080/contacts/6a021681e7af8279068f4b2e

### LOCAL — Create (Grace Hopper)
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Grace",
  "lastName": "Hopper",
  "email": "grace.hopper@example.com",
  "favoriteColor": "navy",
  "birthday": "1906-12-09"
}

### LOCAL — Update (Bob Ross)
PUT http://localhost:8080/contacts/6a021681e7af8279068f4b2e HTTP/1.1
Content-Type: application/json

{
  "firstName": "Bob",
  "lastName": "Ross",
  "email": "happytrees@example.com",
  "favoriteColor": "green",
  "birthday": "1942-10-29"
}

### LOCAL — Delete (Bob Ross)
DELETE http://localhost:8080/contacts/6a021681e7af8279068f4b2e

### PROD — Get all
GET https://cse-341-project1-kvte.onrender.com/contacts

### PROD — Get single (Bob Ross)
GET https://cse-341-project1-kvte.onrender.com/contacts/6a021681e7af8279068f4b2e

### PROD — Create (Grace Hopper)
POST https://cse-341-project1-kvte.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Grace",
  "lastName": "Hopper",
  "email": "grace.hopper@example.com",
  "favoriteColor": "navy",
  "birthday": "1906-12-09"
}

### PROD — Update (Bob Ross)
PUT https://cse-341-project1-kvte.onrender.com/contacts/6a021681e7af8279068f4b2e HTTP/1.1
Content-Type: application/json

{
  "firstName": "Bob",
  "lastName": "Ross",
  "email": "happytrees@example.com",
  "favoriteColor": "green",
  "birthday": "1942-10-29"
}

### PROD — Delete (Bob Ross)
DELETE https://cse-341-project1-kvte.onrender.com/contacts/6a021681e7af8279068f4b2e